packages:
  - configs/*
  - packages/*
  - packages-private/*
  - turbo/*

onlyBuiltDependencies:
  - core-js-pure
  - esbuild
  - msw

catalog:
  yaml: ^2.8.1
  valibot: ^1.1.0
  '@adobe/aio-lib-core-logging': ^3.0.2
  '@adobe/aio-lib-files': ^4.1.2
  '@adobe/aio-lib-state': ^5.3.1
