import { writeFile } from "node:fs/promises";
import { join } from "node:path";

import { isMap, YAMLMap, YAMLSeq } from "yaml";

import {
  CONFIG_SCHEMA_FILE_NAME,
  EXTENSION_POINT_FOLDER_PATH,
  GENERATED_ACTIONS_PATH,
  GENERATED_PATH,
  PACKAGE_NAME,
} from "#commands/constants";
import { detectPackageManager, getExecCommand } from "#commands/init/lib";
import { makeOutputDirFor } from "#commands/utils";
import {
  getOrCreateMap,
  getOrCreateSeq,
  readYamlFile,
} from "#commands/yaml-helpers";

import { ACTION_INPUTS, RUNTIME_ACTIONS } from "./constants";

import type { Document } from "yaml";
import type { ActionConfig } from "./types";

/** Update the ext.config.yaml file */
export async function updateExtConfig() {
  process.stdout.write("📝 Updating ext.config.yaml...\n");

  const outputDir = await makeOutputDirFor(EXTENSION_POINT_FOLDER_PATH);
  const extConfigPath = join(outputDir, "ext.config.yaml");
  const extConfigDoc = await readYamlFile(extConfigPath);

  buildHooks(extConfigDoc);
  buildOperations(extConfigDoc);
  buildRuntimeManifest(extConfigDoc);

  await writeExtConfig(extConfigPath, extConfigDoc);
}

/**
 * Build the definition for a runtime action
 * @param action - The action config
 */
function buildActionDefinition(name: string, action: ActionConfig) {
  const actionDef: YAMLMap = new YAMLMap();
  const inputs = {
    LOG_LEVEL: "$LOG_LEVEL",
  };

  if (action.requiresCommerce) {
    Object.assign(inputs, ACTION_INPUTS);
  }

  actionDef.set("function", `${GENERATED_ACTIONS_PATH}/${name}.js`);
  actionDef.set("web", "yes");
  actionDef.set("runtime", "nodejs:22");
  actionDef.set("inputs", inputs);
  actionDef.set("annotations", {
    "require-adobe-auth": true,
    final: true,
  });

  if (action.requiresSchema) {
    const seq = new YAMLSeq();
    seq.items.push([
      `${GENERATED_PATH}/${CONFIG_SCHEMA_FILE_NAME}`,
      `${PACKAGE_NAME}/`,
    ]);

    seq.flow = true;
    actionDef.set("include", seq);
  }

  return actionDef;
}

/**
 * Build the `operations` section of the `ext.config.yaml` file
 * @param extConfig - The ext.config.yaml file
 */
function buildOperations(extConfig: Document) {
  getOrCreateMap(extConfig, ["operations"], {
    onBeforeCreate: (pair) => {
      pair.key.spaceBefore = true;
    },
  });

  const workerProcess = getOrCreateSeq(
    extConfig,
    ["operations", "workerProcess"],
    {
      onBeforeCreate: (pair) => {
        pair.key.commentBefore =
          " This worker processes definitions are auto-generated by `@adobe/aio-commerce-lib-config`. Do not remove or manually edit.";
      },
    },
  );

  const ourOps = RUNTIME_ACTIONS.map((action) => ({
    type: "action" as const,
    impl: `${PACKAGE_NAME}/${action.name}`,
  }));

  const missingOps = ourOps.filter(
    (op) =>
      workerProcess.items.find(
        (item) => isMap(item) && item.get("impl") === op.impl,
      ) === undefined,
  );

  workerProcess.items.push(
    ...missingOps.map((op) => {
      const map = new YAMLMap();
      map.set("type", op.type);
      map.set("impl", op.impl);

      return map;
    }),
  );
}

/**
 * Build the `runtimeManifest` section of the `ext.config.yaml` file
 * @param extConfig - The ext.config.yaml file
 */
function buildRuntimeManifest(extConfig: Document) {
  getOrCreateMap(extConfig, ["runtimeManifest"]);
  getOrCreateMap(extConfig, ["runtimeManifest", "packages"]);

  const packageDef = getOrCreateMap(
    extConfig,
    ["runtimeManifest", "packages", PACKAGE_NAME],
    {
      onBeforeCreate: (pair) => {
        pair.key.commentBefore =
          " This package definition is auto-generated by `@adobe/aio-commerce-lib-config`. Do not remove or manually edit.";
      },
    },
  );

  const actions = new YAMLMap();
  if (!isMap(actions)) {
    throw new Error(
      "The `actions` field in the package definition is not a map.",
    );
  }

  packageDef.set("license", "Apache-2.0");
  packageDef.set("actions", actions);

  for (const action of RUNTIME_ACTIONS) {
    if (actions.has(action.name)) {
      continue;
    }

    const actionDef = buildActionDefinition(action.name, action);
    actions.set(action.name, actionDef);
  }
}

/**
 * Build the `hooks` section of the `ext.config.yaml` file
 * @param extConfig - The ext.config.yaml file
 */
async function buildHooks(extConfig: Document) {
  const hooks = getOrCreateMap(extConfig, ["hooks"], {
    onBeforeCreate: (pair) => {
      pair.key.spaceBefore = true;
      pair.key.commentBefore =
        " The `pre-app-build` hook is auto-generated by `@adobe/aio-commerce-lib-config`. Do not remove or manually edit.";
    },
  });

  const packageManager = await detectPackageManager();
  const execCommand = getExecCommand(packageManager);

  const command = `${execCommand} @adobe/aio-commerce-lib-config generate schema`;
  const prevValue = (
    (hooks.get("pre-app-build") as string | undefined) ?? ""
  ).trim();

  if (prevValue.endsWith("js") || prevValue.endsWith("ts")) {
    throw new Error(
      "Conflicting pre-app-build hook definition found. The hook needs to be a command in order for `@adobe/aio-commerce-lib-config` to work, not a script.",
    );
  }

  if (!prevValue.includes(command)) {
    hooks.set("pre-app-build", `${prevValue} && ${command}`);
  } else if (prevValue === "") {
    hooks.set("pre-app-build", command);
  }
}

/**
 * Write the ext.config.yaml file
 * @param configPath - The path to the ext.config.yaml file
 * @param config - The config to write
 */
async function writeExtConfig(configPath: string, doc: Document) {
  const yamlContent = doc.toString({
    indent: 2,
    lineWidth: 0,
    defaultStringType: "PLAIN",
  });

  await writeFile(configPath, yamlContent, "utf-8");
}
