/*
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

import { existsSync } from "node:fs";
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, extname, join, relative, sep } from "node:path";

import {
  detectPackageManager,
  getPackageDependencyInstallPlan,
  getProjectRootDirectory,
  loadPackageJson,
  makeOutputDirFor,
  mergePackageJsonDependencies,
} from "@aio-commerce-sdk/scripting-utils/project";
import { createOrUpdateExtConfig } from "@aio-commerce-sdk/scripting-utils/yaml";
import { readYamlFile } from "@aio-commerce-sdk/scripting-utils/yaml/index";
import { consola } from "consola";
import { formatTree } from "consola/utils";
import { build } from "esbuild";

import {
  APP_CONFIG_IMPORT_ALIAS,
  BACKEND_UI_V2_EXTENSION_POINT_ID,
  CONFIGURATION_EXTENSION_POINT_ID,
  EXTENSIBILITY_EXTENSION_POINT_ID,
  getExtensionPointFolderPath,
} from "#commands/constants";
import {
  getActionPath,
  getActionsDir,
  getExtConfigPath,
  getManifestPath,
  getRuntimeAppConfigPath,
  hasDynamicAppConfig,
  runProjectInstall,
} from "#commands/utils";
import {
  hasCustomInstallationSteps,
  resolveCommerceAppConfig,
} from "#config/index";

import {
  buildAdminUiV2ExtConfig,
  buildAppManagementExtConfig,
  buildBusinessConfigurationExtConfig,
} from "./config";
import {
  CUSTOM_IMPORTS_PLACEHOLDER,
  CUSTOM_SCRIPTS_LOADER_PLACEHOLDER,
  CUSTOM_SCRIPTS_MAP_PLACEHOLDER,
  JSX_FILE_EXTENSION,
  TEMPLATES_DIR,
  TSX_FILE_EXTENSION,
  TYPESCRIPT_CONFIG_EXTENSIONS,
  WEB_SOURCE_DEPENDENCIES,
  WEB_SOURCE_DEV_DEPENDENCIES,
  WEB_SOURCE_IMPORT_ALIAS,
  WEB_SOURCE_SHARED_BUNDLES,
} from "./constants";

import type { ExtConfig } from "@aio-commerce-sdk/scripting-utils/yaml";
import type { CommerceAppConfigOutputModel } from "#config/schema/app";
import type { CustomInstallationStep } from "#config/schema/installation";
import type { TemplateAction } from "./config";

type ValidExtensionPointId =
  | typeof EXTENSIBILITY_EXTENSION_POINT_ID
  | typeof CONFIGURATION_EXTENSION_POINT_ID
  | typeof BACKEND_UI_V2_EXTENSION_POINT_ID;

type WebSourceExtension = "jsx" | "tsx";

const LEADING_DOT_SLASH_PATTERN = /^\.\//u;
/** Normalize a path for use as an ESM import specifier. */
function normalizeImportPath(path: string) {
  const normalizedPath = path.split(sep).join("/");
  return normalizedPath.startsWith(".")
    ? normalizedPath
    : `./${normalizedPath}`;
}

/** Normalize a generated file path for package.json imports. */
function normalizePackageJsonPath(path: string) {
  return normalizeImportPath(path).replace(LEADING_DOT_SLASH_PATTERN, "./");
}

/** Add or update the package import alias used by dynamic generated actions. */
async function updateAppConfigImportAlias(
  projectRoot: string,
  runtimeConfigPath: string,
) {
  const pkg = await loadPackageJson(projectRoot);
  if (pkg === null) {
    throw new Error("Could not find package.json.");
  }

  const existingImports =
    typeof pkg.content.imports === "object" && pkg.content.imports !== null
      ? pkg.content.imports
      : {};

  pkg.update({
    imports: {
      ...existingImports,
      [APP_CONFIG_IMPORT_ALIAS]: normalizePackageJsonPath(runtimeConfigPath),
    },
  });

  await pkg.save();
}

/** Write an ESM passthrough module that re-exports an app config file. */
async function writeJavaScriptAppConfigModule(
  configFilePath: string,
  outputPath: string,
) {
  const configImportPath = normalizeImportPath(
    relative(dirname(outputPath), configFilePath),
  );

  // JSON imports require an import attribute under Node's ESM loader.
  const importAttributes =
    extname(configFilePath) === ".json" ? ' with { type: "json" }' : "";

  await writeFile(
    outputPath,
    [
      "// This file has been auto-generated by `@adobe/aio-commerce-lib-app`",
      "// Do not modify this file directly",
      "",
      `import appConfig from "${configImportPath}"${importAttributes};`,
      "",
      "export default appConfig;",
      "",
    ].join("\n"),
    "utf-8",
  );
}

/** Bundle a TypeScript app config file into runtime-safe ESM. */
async function bundleTypeScriptAppConfigModule(
  configFilePath: string,
  outputPath: string,
) {
  await build({
    entryPoints: [configFilePath],
    outfile: outputPath,
    bundle: true,
    format: "esm",
    platform: "node",
    target: "node22",
    packages: "external",
    logLevel: "silent",
  });
}

/** Generate the runtime-safe app config module used by generated runtime actions. */
async function generateRuntimeAppConfigModule() {
  const projectRoot = await getProjectRootDirectory();
  const runtimeConfigPath = getRuntimeAppConfigPath();
  await makeOutputDirFor(dirname(runtimeConfigPath));
  const outputPath = join(projectRoot, runtimeConfigPath);
  const configFilePath = await resolveCommerceAppConfig(projectRoot);

  if (!configFilePath) {
    throw new Error(
      "Dynamic list options require an app.commerce.config.* file so generated actions can import the option factories at runtime.",
    );
  }

  consola.info("Generating JS config module...");

  if (TYPESCRIPT_CONFIG_EXTENSIONS.has(extname(configFilePath))) {
    await bundleTypeScriptAppConfigModule(configFilePath, outputPath);
  } else {
    await writeJavaScriptAppConfigModule(configFilePath, outputPath);
  }

  await updateAppConfigImportAlias(projectRoot, runtimeConfigPath);
  consola.success(
    `Generated JS config module: ${relative(process.cwd(), outputPath)}`,
  );
}

/**
 * Write an ESM module that re-exports the static app manifest JSON so generated
 * actions can import it via the alias without needing a JSON import attribute.
 */
async function prepareStaticAppConfigImportAlias() {
  const projectRoot = await getProjectRootDirectory();
  const runtimeConfigPath = getRuntimeAppConfigPath();
  const outputPath = join(projectRoot, runtimeConfigPath);

  await makeOutputDirFor(dirname(runtimeConfigPath));
  await writeJavaScriptAppConfigModule(
    join(projectRoot, getManifestPath()),
    outputPath,
  );

  await updateAppConfigImportAlias(projectRoot, runtimeConfigPath);
}

/**
 * Prepare runtime-side config artifacts consumed by generated actions: the
 * bundled ESM module and its `#app.commerce.config` package import alias.
 *
 * Dynamic schemas use the source config file, while static schemas use the generated JSON manifest.
 */
export async function prepareRuntimeAppConfigModule(
  appManifest: CommerceAppConfigOutputModel,
) {
  if (hasDynamicAppConfig(appManifest)) {
    await generateRuntimeAppConfigModule();
    return;
  }

  await prepareStaticAppConfigImportAlias();
}

/**
 * Read an extension point's ext.config.yaml file and return it as a JS object.
 * @param extensionPointId - The extension point ID to read the config for.
 */
export async function readExtConfig(extensionPointId: ValidExtensionPointId) {
  const extConfigPath = join(
    await getProjectRootDirectory(),
    getExtConfigPath(extensionPointId),
  );

  try {
    return {
      path: extConfigPath,
      doc: await readYamlFile(extConfigPath),
    };
  } catch (error) {
    const reason =
      error instanceof Error
        ? error.message
        : "Unexpected error while reading the file.";

    throw new Error(
      [
        `Could not read ext.config.yaml for ${extensionPointId} at ${extConfigPath}.`,
        `Make sure the file exists and is valid YAML. You can regenerate it with "aio-commerce-lib-app generate actions".`,
        `Reason: ${reason}`,
      ].join("\n"),
    );
  }
}

/** Update the ext.config.yaml file */
export async function updateExtConfig(
  appConfig: CommerceAppConfigOutputModel,
  extensionPointId: ValidExtensionPointId,
) {
  consola.info(`Updating ext.config.yaml for ${extensionPointId}...`);

  await makeOutputDirFor(getExtensionPointFolderPath(extensionPointId));
  const { path: extConfigPath, doc: extConfigDoc } =
    await readExtConfig(extensionPointId);

  let extConfig: ExtConfig;

  // biome-ignore lint/style/useDefaultSwitchClause: The function can only be called with the two defined extension point IDs, so a default case is not necessary
  switch (extensionPointId) {
    case EXTENSIBILITY_EXTENSION_POINT_ID: {
      extConfig = buildAppManagementExtConfig(appConfig);
      break;
    }

    case CONFIGURATION_EXTENSION_POINT_ID: {
      extConfig = buildBusinessConfigurationExtConfig();
      break;
    }

    case BACKEND_UI_V2_EXTENSION_POINT_ID: {
      extConfig = buildAdminUiV2ExtConfig(appConfig);
      break;
    }
  }

  await createOrUpdateExtConfig(extConfigPath, extConfig, extConfigDoc);
  return extConfig;
}

/**
 * Resolve the generated web-src entrypoint path from an extension config.
 * @param extConfig - Extension config containing the view operation.
 * @param extensionPointId - Extension point that owns the web source folder.
 */
function getWebSourceEntrypoint(
  extConfig: ExtConfig,
  extensionPointId: ValidExtensionPointId,
) {
  const viewEntrypoint = extConfig.operations?.view?.[0]?.impl;
  if (viewEntrypoint === undefined) {
    return null;
  }

  return join(
    getExtensionPointFolderPath(extensionPointId),
    extConfig.web ?? "web-src",
    viewEntrypoint,
  );
}

/**
 * Ensure package.json has the dependencies and Parcel config needed by web-src.
 * @param projectRoot - Project root containing the package.json to update.
 */
async function prepareWebSourcePackage(projectRoot: string) {
  const pkg = await loadPackageJson(projectRoot);
  if (pkg === null) {
    throw new Error("Could not find package.json.");
  }

  const installPlan = await getPackageDependencyInstallPlan(
    [...WEB_SOURCE_DEPENDENCIES, ...WEB_SOURCE_DEV_DEPENDENCIES],
    projectRoot,
  );

  if (installPlan.incompatible.length > 0) {
    const incompatibleDependencies = installPlan.incompatible
      .map(
        ({ name, version, installedVersion }) =>
          `${name}@${installedVersion} does not satisfy ${version}`,
      )
      .join("\n");

    throw new Error(
      `Cannot scaffold web-src because installed dependencies are incompatible:\n${incompatibleDependencies}`,
    );
  }

  const dependencies = pkg.content.dependencies ?? {};
  const devDependencies = pkg.content.devDependencies ?? {};
  const dependencyMaps = [dependencies, devDependencies];
  const declaredDependencyNames = new Set(
    dependencyMaps.flatMap((dependencies) => Object.keys(dependencies)),
  );
  const dependenciesToDeclare = [
    ...WEB_SOURCE_DEPENDENCIES,
    ...WEB_SOURCE_DEV_DEPENDENCIES,
  ].filter(({ name }) => !declaredDependencyNames.has(name));

  if (dependenciesToDeclare.length > 0) {
    consola.info("Adding web-src dependencies in package.json:");
    consola.log.raw(
      formatTree(
        dependenciesToDeclare.map(({ name, version }) => ` ${name}@${version}`),
      ),
    );
  } else {
    consola.info("web-src dependencies are already declared in package.json.");
  }

  pkg.update({
    dependencies: mergePackageJsonDependencies(
      dependencies,
      WEB_SOURCE_DEPENDENCIES,
      dependencyMaps,
    ),
    devDependencies: mergePackageJsonDependencies(
      devDependencies,
      WEB_SOURCE_DEV_DEPENDENCIES,
      dependencyMaps,
    ),
    // Required as per Spectrum S2 documentation: https://react-spectrum.adobe.com/getting-started#framework-setup
    "@parcel/bundler-default": {
      ...(pkg.content["@parcel/bundler-default"] as Record<string, unknown>),
      manualSharedBundles: WEB_SOURCE_SHARED_BUNDLES,
    },
    // Required otherwise Parcel will fail when using our deps which export ESM.
    "@parcel/resolver-default": {
      ...(pkg.content["@parcel/resolver-default"] as Record<string, unknown>),
      packageExports: true,
    },
  });

  await pkg.save();

  if (installPlan.missing.length === 0) {
    consola.info("web-src dependencies are already installed.");
    return;
  }

  consola.info("Installing missing web-src dependencies from package.json:");
  consola.log.raw(
    formatTree(
      installPlan.missing.map(({ name, version }) => ` ${name}@${version}`),
    ),
  );
  const packageManager = await detectPackageManager(projectRoot);
  runProjectInstall(packageManager, projectRoot);
}

/**
 * Add the package import alias for an existing or generated web-src.
 * @param extConfig - Extension config containing the view operation.
 */
export async function prepareWebSourceImportAlias(extConfig: ExtConfig) {
  const entrypoint = getWebSourceEntrypoint(
    extConfig,
    BACKEND_UI_V2_EXTENSION_POINT_ID,
  );

  if (entrypoint === null) {
    return;
  }

  const projectRoot = await getProjectRootDirectory();
  const pkg = await loadPackageJson(projectRoot);
  if (pkg === null) {
    throw new Error("Could not find package.json.");
  }

  const existingImports =
    typeof pkg.content.imports === "object" && pkg.content.imports !== null
      ? pkg.content.imports
      : {};

  const webSourceSrcPath = join(dirname(entrypoint), "src");
  pkg.update({
    imports: {
      ...existingImports,
      [WEB_SOURCE_IMPORT_ALIAS]: `${normalizePackageJsonPath(
        webSourceSrcPath,
      )}/*`,
    },
  });

  await pkg.save();
}

/**
 * Resolve the generated web-src file extension from the app config file type.
 * @param projectRoot - Project root used to find the commerce app config file.
 */
async function resolveWebSourceExtension(
  projectRoot: string,
): Promise<WebSourceExtension> {
  const configFilePath = await resolveCommerceAppConfig(projectRoot);
  return configFilePath !== null &&
    TYPESCRIPT_CONFIG_EXTENSIONS.has(extname(configFilePath))
    ? "tsx"
    : "jsx";
}

/**
 * Resolve the destination path for a web-src template file.
 * @param templatePath - Template file path relative to its source directory.
 * @param extension - Web source extension to generate.
 */
function getWebSourceTemplateTargetPath(
  templatePath: string,
  extension: WebSourceExtension,
) {
  if (extension === "jsx" || !templatePath.endsWith(JSX_FILE_EXTENSION)) {
    return templatePath;
  }

  return `${templatePath.slice(0, -JSX_FILE_EXTENSION.length)}${TSX_FILE_EXTENSION}`;
}

/**
 * Copy web-src templates directly to the final file extension and entrypoint.
 * @param sourceDir - Template web-src directory.
 * @param targetDir - Generated web-src directory.
 * @param extension - Web source extension to generate.
 */
async function copyWebSourceTemplates(
  sourceDir: string,
  targetDir: string,
  extension: WebSourceExtension,
) {
  await mkdir(targetDir, { recursive: true });
  const outputFiles: string[] = [];

  for (const entry of await readdir(sourceDir, { withFileTypes: true })) {
    const sourcePath = join(sourceDir, entry.name);
    const targetPath = join(
      targetDir,
      getWebSourceTemplateTargetPath(entry.name, extension),
    );

    if (entry.isDirectory()) {
      outputFiles.push(
        ...(await copyWebSourceTemplates(sourcePath, targetPath, extension)),
      );

      continue;
    }

    let content = await readFile(sourcePath, "utf-8");

    if (extension === "tsx") {
      content = content.replaceAll(
        `${JSX_FILE_EXTENSION}"`,
        `${TSX_FILE_EXTENSION}"`,
      );
    }

    await writeFile(targetPath, content, { encoding: "utf-8", flag: "wx" });
    outputFiles.push(` ${relative(process.cwd(), targetPath)}`);
  }

  return outputFiles;
}

/** Generate the web source scaffold for iframe-based Admin UI extensions. */
export async function generateWebSrc(
  extConfig: ExtConfig,
  extensionPointId: ValidExtensionPointId,
  templatesDir = TEMPLATES_DIR,
) {
  const entrypoint = getWebSourceEntrypoint(extConfig, extensionPointId);
  if (entrypoint === null) {
    return;
  }

  const projectRoot = await getProjectRootDirectory();
  const entrypointPath = join(projectRoot, entrypoint);

  if (existsSync(entrypointPath)) {
    consola.info(
      `web-src entrypoint already exists, skipping scaffold: ${relative(
        process.cwd(),
        entrypointPath,
      )}`,
    );
    return;
  }

  consola.start(`Scaffolding web-src for ${extensionPointId}...`);

  const sourceDir = join(templatesDir, "admin-ui", "web-src");
  const targetDir = dirname(entrypointPath);

  const outputFiles = await copyWebSourceTemplates(
    sourceDir,
    targetDir,
    await resolveWebSourceExtension(projectRoot),
  );

  await prepareWebSourcePackage(projectRoot);

  consola.success(`Scaffolded ${relative(process.cwd(), targetDir)}`);
  consola.log.raw(formatTree(outputFiles));
}

/** Generate the action files */
export async function generateActionFiles(
  appManifest: CommerceAppConfigOutputModel,
  actions: TemplateAction[],
  extensionPointId: ValidExtensionPointId,
  templatesDir: string,
) {
  consola.start("Generating runtime actions...");

  await makeOutputDirFor(getActionsDir(extensionPointId));
  const projectRoot = await getProjectRootDirectory();
  const outputFiles: string[] = [];

  for (const action of actions) {
    const templatePath = join(templatesDir, action.templateFile);
    let template = await readFile(templatePath, "utf-8");

    // For installation action, inject custom script imports
    if (action.name === "installation") {
      const customScriptsTemplatePath = join(
        templatesDir,
        "app-management",
        "custom-scripts.js.template",
      );

      const scriptsTemplate = await generateCustomScriptsTemplate(
        await readFile(customScriptsTemplatePath, "utf-8"),
        appManifest,
      );

      template = applyCustomScripts(template, scriptsTemplate);
    }

    const actionPath = join(
      projectRoot,
      getActionPath(extensionPointId, action.name),
    );

    await writeFile(actionPath, template, "utf-8");
    outputFiles.push(` ${relative(process.cwd(), actionPath)}`);
  }

  consola.success(`Generated ${actions.length} action(s)`);
  consola.log.raw(formatTree(outputFiles));
}

/**
 * Applies the given custom scripts template code to the given installation template.
 * @param installationTemplate - The installation code runtime action template
 * @param customScriptsTemplate - The custom scripts dynamically generated template.
 */
export function applyCustomScripts(
  installationTemplate: string,
  customScriptsTemplate: string | null,
) {
  // There are scripts file to include.
  if (customScriptsTemplate !== null) {
    return installationTemplate
      .replace(CUSTOM_SCRIPTS_LOADER_PLACEHOLDER, customScriptsTemplate)
      .replace(
        "const args = { appConfig };",
        "const args = { appConfig, customScriptsLoader };",
      );
  }
  // No custom scripts, remove the loader references
  consola.debug(
    "No custom installation steps found, skipping custom-scripts.js generation...",
  );

  return installationTemplate.replace(
    CUSTOM_SCRIPTS_LOADER_PLACEHOLDER,
    "// No custom installation scripts configured",
  );
}

/**
 * Generate the installation template with dynamic custom script imports
 */
export async function generateCustomScriptsTemplate(
  template: string,
  appManifest: CommerceAppConfigOutputModel,
) {
  if (!hasCustomInstallationSteps(appManifest)) {
    return null;
  }

  // We need to resolve paths from project root to relative imports from the
  // generated installation action's location.
  const projectRoot = await getProjectRootDirectory();
  const installationActionDir = join(
    projectRoot,
    getActionsDir(EXTENSIBILITY_EXTENSION_POINT_ID),
  );

  // Generate import statements
  const customSteps = appManifest.installation.customInstallationSteps;
  const importStatements = customSteps
    .map((step: CustomInstallationStep, index: number) => {
      // step.script is relative to project root (e.g., "./scripts/setup.js")
      const absoluteScriptPath = join(projectRoot, step.script);
      let relativeImportPath = relative(
        installationActionDir,
        absoluteScriptPath,
      );

      if (!relativeImportPath.startsWith(".")) {
        relativeImportPath = `./${relativeImportPath}`;
      }

      relativeImportPath = relativeImportPath.replace(/\\/g, "/");

      const importName = `customScript${index}`;
      return `import * as ${importName} from "${relativeImportPath}";`;
    })
    .join("\n");

  // Generate the loadCustomInstallationScripts function
  const scriptMap = customSteps
    .map((step: CustomInstallationStep, index: number) => {
      const scriptPath = step.script;
      const importName = `customScript${index}`;
      const entry = `"${scriptPath}": ${importName},`;

      return entry.padStart(entry.length + 6); // add indentation
    })
    .join("\n");

  // Inject imports and function into template
  const result = template.replace(CUSTOM_IMPORTS_PLACEHOLDER, importStatements);
  return result.replace(CUSTOM_SCRIPTS_MAP_PLACEHOLDER, scriptMap);
}
