/*
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

import { spawnSync } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, extname, join, relative, sep } from "node:path";

import {
  detectPackageManager,
  getPackageExecutionCommand,
  getProjectRootDirectory,
  loadPackageJson,
  makeOutputDirFor,
} from "@aio-commerce-sdk/scripting-utils/project";
import { createOrUpdateExtConfig } from "@aio-commerce-sdk/scripting-utils/yaml";
import { readYamlFile } from "@aio-commerce-sdk/scripting-utils/yaml/index";
import { consola } from "consola";
import { formatTree } from "consola/utils";

import {
  APP_CONFIG_IMPORT_ALIAS,
  BACKEND_UI_V2_EXTENSION_POINT_ID,
  CONFIGURATION_EXTENSION_POINT_ID,
  EXTENSIBILITY_EXTENSION_POINT_ID,
  getExtensionPointFolderPath,
} from "#commands/constants";
import {
  getActionPath,
  getActionsDir,
  getExtConfigPath,
  getManifestPath,
  getRuntimeAppConfigPath,
  requiresJavaScriptAppConfig,
} from "#commands/utils";
import {
  hasCustomInstallationSteps,
  isTypeScriptConfig,
  resolveCommerceAppConfig,
} from "#config/index";

import {
  buildAdminUiV2ExtConfig,
  buildAppManagementExtConfig,
  buildBusinessConfigurationExtConfig,
} from "./config";
import {
  CUSTOM_IMPORTS_PLACEHOLDER,
  CUSTOM_SCRIPTS_LOADER_PLACEHOLDER,
  CUSTOM_SCRIPTS_MAP_PLACEHOLDER,
} from "./constants";

import type { ExtConfig } from "@aio-commerce-sdk/scripting-utils/yaml";
import type { CommerceAppConfigOutputModel } from "#config/schema/app";
import type { CustomInstallationStep } from "#config/schema/installation";
import type { TemplateAction } from "./config";

type ValidExtensionPointId =
  | typeof EXTENSIBILITY_EXTENSION_POINT_ID
  | typeof CONFIGURATION_EXTENSION_POINT_ID
  | typeof BACKEND_UI_V2_EXTENSION_POINT_ID;

const ESBUILD_PACKAGE = "esbuild@0.28.0";
const LEADING_DOT_SLASH_PATTERN = /^\.\//u;

/** Normalize a path for use as an ESM import specifier. */
function normalizeImportPath(path: string) {
  const normalizedPath = path.split(sep).join("/");
  return normalizedPath.startsWith(".")
    ? normalizedPath
    : `./${normalizedPath}`;
}

/** Normalize a generated file path for package.json imports. */
function normalizePackageJsonPath(path: string) {
  return normalizeImportPath(path).replace(LEADING_DOT_SLASH_PATTERN, "./");
}

/** Add or update the package import alias used by dynamic generated actions. */
async function updateAppConfigImportAlias(
  projectRoot: string,
  runtimeConfigPath: string,
) {
  const pkg = await loadPackageJson(projectRoot);
  if (pkg === null) {
    throw new Error("Could not find package.json.");
  }

  const existingImports =
    typeof pkg.content.imports === "object" && pkg.content.imports !== null
      ? pkg.content.imports
      : {};

  pkg.update({
    imports: {
      ...existingImports,
      [APP_CONFIG_IMPORT_ALIAS]: normalizePackageJsonPath(runtimeConfigPath),
    },
  });

  await pkg.save();
}

/** Write an ESM passthrough module that re-exports an app config file. */
async function writeJavaScriptAppConfigModule(
  configFilePath: string,
  outputPath: string,
) {
  const configImportPath = normalizeImportPath(
    relative(dirname(outputPath), configFilePath),
  );

  // JSON imports require an import attribute under Node's ESM loader.
  const isJson = extname(configFilePath) === ".json";
  const importAttributes = isJson ? ' with { type: "json" }' : "";

  await writeFile(
    outputPath,
    [
      "// This file has been auto-generated by `@adobe/aio-commerce-lib-app`",
      "// Do not modify this file directly",
      "",
      `import appConfig from "${configImportPath}"${importAttributes};`,
      "",
      // JSON can't have any exports other than the default one.
      isJson ? null : `export * from "${configImportPath}";`,
      "export default appConfig;",
      "",
    ]
      .filter((item) => item !== null)
      .join("\n"),
    "utf-8",
  );
}

/** Bundle a TypeScript app config file into runtime-safe ESM. */
async function bundleTypeScriptAppConfigModule(
  configFilePath: string,
  outputPath: string,
) {
  const projectRoot = await getProjectRootDirectory();
  const packageManager = await detectPackageManager(projectRoot);

  const { command, args } = getPackageExecutionCommand(
    packageManager,
    [
      ESBUILD_PACKAGE,
      configFilePath,
      "--bundle",
      "--format=esm",
      "--log-level=silent",
      `--outfile=${outputPath}`,
      "--packages=external",
      "--platform=node",
      "--target=node22",
    ],
    { allowBuild: "esbuild" },
  );

  const result = spawnSync(command, args, {
    cwd: projectRoot,
    stdio: "inherit",
  });

  if (result.error || result.status !== 0) {
    throw new Error(
      `Could not bundle the TypeScript app config with ${ESBUILD_PACKAGE}.`,
      {
        cause:
          result.error ??
          new Error(`Bundle command exited with code ${result.status}`),
      },
    );
  }
}

/**
 * Write an ESM module that re-exports the static app manifest JSON so generated
 * actions can import it via the alias without needing a JSON import attribute.
 */
async function prepareStaticAppConfigImportAlias() {
  const projectRoot = await getProjectRootDirectory();
  const runtimeConfigPath = getRuntimeAppConfigPath();
  const outputPath = join(projectRoot, runtimeConfigPath);

  await makeOutputDirFor(dirname(runtimeConfigPath));
  await writeJavaScriptAppConfigModule(
    join(projectRoot, getManifestPath()),
    outputPath,
  );
}

/**
 * Prepare the runtime config module consumed by generated actions and its
 * `#app.commerce.config` package import alias.
 *
 * TypeScript configs are bundled into a generated runtime module. JavaScript
 * configs use a passthrough module, while serializable default-only configs use
 * a re-export of the validated JSON manifest.
 */
export async function prepareRuntimeAppConfigModule(
  appManifest: CommerceAppConfigOutputModel,
) {
  const projectRoot = await getProjectRootDirectory();
  const configFilePath = await resolveCommerceAppConfig(projectRoot);

  if (await requiresJavaScriptAppConfig(appManifest)) {
    if (configFilePath === null) {
      throw new Error(
        "Generating a runtime config module requires an app.commerce.config.* file.",
      );
    }

    await makeOutputDirFor(dirname(getRuntimeAppConfigPath()));
    const outputPath = join(projectRoot, getRuntimeAppConfigPath());

    if (isTypeScriptConfig(configFilePath)) {
      await bundleTypeScriptAppConfigModule(configFilePath, outputPath);
    } else {
      await writeJavaScriptAppConfigModule(configFilePath, outputPath);
    }
  } else {
    await prepareStaticAppConfigImportAlias();
  }

  await updateAppConfigImportAlias(projectRoot, getRuntimeAppConfigPath());
}

/**
 * Read an extension point's ext.config.yaml file and return it as a JS object.
 * @param extensionPointId - The extension point ID to read the config for.
 */
export async function readExtConfig(extensionPointId: ValidExtensionPointId) {
  const extConfigPath = join(
    await getProjectRootDirectory(),
    getExtConfigPath(extensionPointId),
  );

  try {
    return {
      doc: await readYamlFile(extConfigPath),
      path: extConfigPath,
    };
  } catch (error) {
    const reason =
      error instanceof Error
        ? error.message
        : "Unexpected error while reading the file.";

    throw new Error(
      [
        `Could not read ext.config.yaml for ${extensionPointId} at ${extConfigPath}.`,
        `Make sure the file exists and is valid YAML. You can regenerate it with "aio-commerce-lib-app generate actions".`,
        `Reason: ${reason}`,
      ].join("\n"),
      { cause: error },
    );
  }
}

/** Update the ext.config.yaml file */
export async function updateExtConfig(
  appConfig: CommerceAppConfigOutputModel,
  extensionPointId: ValidExtensionPointId,
) {
  consola.info(`Updating ext.config.yaml for ${extensionPointId}...`);

  await makeOutputDirFor(getExtensionPointFolderPath(extensionPointId));
  const { path: extConfigPath, doc: extConfigDoc } =
    await readExtConfig(extensionPointId);

  let extConfig: ExtConfig;

  switch (extensionPointId) {
    case EXTENSIBILITY_EXTENSION_POINT_ID: {
      extConfig = buildAppManagementExtConfig(appConfig);
      break;
    }

    case CONFIGURATION_EXTENSION_POINT_ID: {
      extConfig = buildBusinessConfigurationExtConfig();
      break;
    }

    case BACKEND_UI_V2_EXTENSION_POINT_ID: {
      extConfig = buildAdminUiV2ExtConfig(appConfig);
      break;
    }

    default: {
      throw new Error(`Unsupported extension point: ${extensionPointId}`);
    }
  }

  await createOrUpdateExtConfig(extConfigPath, extConfig, extConfigDoc);
  return extConfig;
}

/** Generate the action files */
export async function generateActionFiles(
  appManifest: CommerceAppConfigOutputModel,
  actions: TemplateAction[],
  extensionPointId: ValidExtensionPointId,
  templatesDir: string,
) {
  consola.start("Generating runtime actions...");

  await makeOutputDirFor(getActionsDir(extensionPointId));
  const projectRoot = await getProjectRootDirectory();

  const outputFiles = await Promise.all(
    actions.map(async (action) => {
      const templatePath = join(templatesDir, action.templateFile);
      let template = await readFile(templatePath, "utf-8");

      // For installation action, inject custom script imports
      if (action.name === "installation") {
        const customScriptsTemplatePath = join(
          templatesDir,
          "app-management",
          "custom-scripts.js.template",
        );

        const scriptsTemplate = await generateCustomScriptsTemplate(
          await readFile(customScriptsTemplatePath, "utf-8"),
          appManifest,
        );

        template = applyCustomScripts(template, scriptsTemplate);
      }

      const actionPath = join(
        projectRoot,
        getActionPath(extensionPointId, action.name),
      );

      await writeFile(actionPath, template, "utf-8");
      return ` ${relative(process.cwd(), actionPath)}`;
    }),
  );

  consola.success(`Generated ${actions.length} action(s)`);
  consola.log.raw(formatTree(outputFiles));
}

/**
 * Applies the given custom scripts template code to the given installation template.
 * @param installationTemplate - The installation code runtime action template
 * @param customScriptsTemplate - The custom scripts dynamically generated template.
 */
export function applyCustomScripts(
  installationTemplate: string,
  customScriptsTemplate: string | null,
) {
  // There are scripts file to include.
  if (customScriptsTemplate !== null) {
    return installationTemplate
      .replace(CUSTOM_SCRIPTS_LOADER_PLACEHOLDER, customScriptsTemplate)
      .replace(
        "const args = { appConfig };",
        "const args = { appConfig, customScriptsLoader };",
      );
  }
  // No custom scripts, remove the loader references
  consola.debug(
    "No custom installation steps found, skipping custom-scripts.js generation...",
  );

  return installationTemplate.replace(
    CUSTOM_SCRIPTS_LOADER_PLACEHOLDER,
    "// No custom installation scripts configured",
  );
}

/**
 * Generate the installation template with dynamic custom script imports
 */
export async function generateCustomScriptsTemplate(
  template: string,
  appManifest: CommerceAppConfigOutputModel,
) {
  if (!hasCustomInstallationSteps(appManifest)) {
    return null;
  }

  // We need to resolve paths from project root to relative imports from the
  // generated installation action's location.
  const projectRoot = await getProjectRootDirectory();
  const installationActionDir = join(
    projectRoot,
    getActionsDir(EXTENSIBILITY_EXTENSION_POINT_ID),
  );

  // Generate import statements
  const customSteps = appManifest.installation.customInstallationSteps;
  const importStatements = customSteps
    .map((step: CustomInstallationStep, index: number) => {
      // step.script is relative to project root (e.g., "./scripts/setup.js")
      const absoluteScriptPath = join(projectRoot, step.script);
      let relativeImportPath = relative(
        installationActionDir,
        absoluteScriptPath,
      );

      if (!relativeImportPath.startsWith(".")) {
        relativeImportPath = `./${relativeImportPath}`;
      }

      relativeImportPath = relativeImportPath.replace(/\\/g, "/");

      const importName = `customScript${index}`;
      return `import * as ${importName} from "${relativeImportPath}";`;
    })
    .join("\n");

  // Generate the loadCustomInstallationScripts function
  const scriptMap = customSteps
    .map((step: CustomInstallationStep, index: number) => {
      const scriptPath = step.script;
      const importName = `customScript${index}`;
      const entry = `"${scriptPath}": ${importName},`;

      return entry.padStart(entry.length + 6); // add indentation
    })
    .join("\n");

  // Inject imports and function into template
  const result = template.replace(CUSTOM_IMPORTS_PLACEHOLDER, importStatements);
  return result.replace(CUSTOM_SCRIPTS_MAP_PLACEHOLDER, scriptMap);
}
