name: Notify on release

on:
  release:
    types: [published]

jobs:
  notify:
    name: Notify new release
    runs-on: ubuntu-latest
    steps:
      - name: "Notify on #commerce-extensibility"
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ secrets.TEST_SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: >
            {
              "text": "${{ github.event.release.name }} has been released. Release notes: ${{ github.event.release.html_url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":adobe_commerce_02: `${{ github.event.release.name }}` has been released. Read the <${{ github.event.release.html_url }}| release notes → >"
                  }
                }
              ]
            }
