name: Notify on release

on:
  release:
    types: [published]

jobs:
  notify:
    name: Notify new release
    runs-on: ubuntu-latest
    steps:
      - name: "Notify on #commerce-extensibility"
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ secrets.TEST_SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: >
            {
              "text": "<${{ github.event.repository.html_url }}|*Adobe Commerce SDK for App Builder*> has been released",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Published new version <${{ github.event.release.html_url }}|${{ github.event.release.name }}>"
                  }
                },
                {
                    "type": "rich_text",
                    "elements": [
                        {
                            "type": "rich_text_quote",
                            "elements": [
                                {
                                    "type": "text",
                                    "text": "${{ github.event.release.body }}"
                                }
                            ]
                        }
                    ]
                }
              ]
            }
