name: Release Shared

on:
  workflow_call:
    inputs:
      channel:
        required: true
        type: string
      base_branch:
        required: true
        type: string

    secrets:
      REGISTRY_URL:
        required: true
      SLACK_WEBHOOK_URL:
        required: true
      REGISTRY_PACKAGE_BASE_URL:
        required: true
      REGISTRY_AUTH_TOKEN:
        required: true
jobs:
  release:
    name: Version or Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # pnpm version will be read from packageManager field in package.json
      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Setup Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: lts/*
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Turbo Build on affected packages
        run: pnpm turbo build --affected

      - name: Prepare release context
        uses: actions/github-script@v8.0.0
        id: prepare
        env:
          BASE_BRANCH: ${{ inputs.base_branch }}
          REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
          REGISTRY_AUTH_TOKEN: ${{ secrets.REGISTRY_AUTH_TOKEN }}
          RELEASE_CHANNEL: ${{ inputs.channel }}
        with:
          script: |
            // Scripts are resolved relative to the root of the repository
            const { default: execPrepare } = await import('${{ github.workspace }}/scripts/source/ci/release/prepare.ts');
            await execPrepare(core, exec);

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@6a0a831ff30acef54f2c6aa1cbbc1096b066edaf # v1.7.0
        with:
          version: pnpm changeset version
          publish: pnpm changeset publish
          commit: "ci: release packages"
          title: "[CI] Release Packages"
          createGithubReleases: ${{ inputs.channel == 'stable' }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Generate Slack Announcement
        id: announcement
        if: steps.changesets.outputs.published == 'true'
        uses: actions/github-script@v8.0.0
        env:
          PUBLISHED_PACKAGES: ${{ steps.changesets.outputs.publishedPackages }}
          REGISTRY_PACKAGE_BASE_URL: ${{ secrets.REGISTRY_PACKAGE_BASE_URL }}
          RELEASE_CHANNEL: ${{ inputs.channel }}
        with:
          script: |
            // Scripts are resolved relative to the root of the repository
            const { default: execAnnouncement } = await import('${{ github.workspace }}/scripts/source/ci/release/announce.ts');
            await execAnnouncement(core);

      - name: Notify on Slack
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
        if: steps.changesets.outputs.published == 'true'
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: ${{ steps.announcement.outputs.SLACK_WEBHOOK_PAYLOAD }}
