name: Publish Internal

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release Internal
    if: github.repository == 'adobe/aio-commerce-sdk'
    uses: ./.github/workflows/publish-shared.yml
    permissions:
      contents: write
      pull-requests: write
      packages: write
      id-token: write
    with:
      channel: internal
    secrets:
      REGISTRY_PACKAGE_BASE_URL: ${{ secrets.ARTIFACTORY_PACKAGE_BASE_URL }}
      REGISTRY_URL: ${{ secrets.ARTIFACTORY_REPO_PUBLISH_URL }}
      REGISTRY_AUTH_TOKEN: ${{ secrets.ARTIFACTORY_API_TOKEN }}

  notify:
    name: Notify Slack
    needs: release
    if: needs.release.outputs.published == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@af78098f536edbc4de71162a307590698245be95 # v2
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: ${{ needs.release.outputs.SLACK_WEBHOOK_PAYLOAD }}
