name: Validate Renovate Config

on:
  pull_request:
    paths:
      - '.github/renovate.json'

jobs:
  validate:
    name: Validate Renovate Configuration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: false

      # See: https://docs.renovatebot.com/config-validation/
      - name: Validate with Renovate CLI
        run: |
          npx --yes --package renovate renovate-config-validator --strict
        env:
          LOG_LEVEL: debug

      - name: Remove validation labels
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          fail_on_error: false
          labels: |
            renovate-config:valid
            renovate-config:invalid

      - name: Add valid label
        uses: actions-ecosystem/action-add-labels@v1
        if: success()
        with:
          labels: renovate-config:valid

      - name: Add invalid label
        uses: actions-ecosystem/action-add-labels@v1
        if: failure()
        with:
          labels: renovate-config:invalid
